version: '3.3'

services:

  wordpress:
    image: harbor.norsys-afrique.ma/clickson/clickson-wp-dev:latest
    env_file:
      - .env
    restart: always
    ports:
    - "8090:80"
    - "8443:443"
    depends_on:
      - db
    environment:
      JWT_AUTH_SECRET_KEY: ${JWT_AUTH_SECRET_KEY}
      JWT_AUTH_CORS_ENABLE: ${JWT_AUTH_CORS_ENABLE}
    volumes:
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./composer.json:/var/www/html/composer.json
  db:
    image: mysql:8.0
    env_file:
      - .env
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: clickson_wp_db
      MYSQL_USER: norsys
      MYSQL_PASSWORD: MDP2naf
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
