version: '3.3'

services:

  wordpress:
    image: harbor.norsys-afrique.ma/clickson/clickson-wp-dev:latest
    env_file:
      - .env
    restart: always
    ports:
      - 8090:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      DOMAINE_PUBLIQUE: ${DOMAINE_PUBLIQUE}
      DOMAINE_ADMIN: ${DOMAINE_ADMIN}
      WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      WORDPRESS_AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT}
      WORDPRESS_SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      GRAPHQL_JWT_AUTH_SECRET_KEY: ${GRAPHQL_JWT_AUTH_SECRET_KEY}
    volumes:
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./composer.json:/var/www/html/composer.json
  db:
    image: mysql:8.0
    env_file:
      - .env
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: clickson_wp_db
      MYSQL_USER: norsys
      MYSQL_PASSWORD: MDP2naf
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
